public class Random_LCG {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object unSeed = (java.util.function.Function<Object, Object>) (v_0) -> v_0;
public static final Object showSeed = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ("Seed ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showIntImpl)).apply(v_0)))));  return __map; } }).get();
public static final Object lcgM = new Integer(2147483647);
public static final Object mkSeed = (java.util.function.Function<Object, Object>) (x_0) -> { Object n_prime__1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply(x_0))).apply(new Integer(2147483645)); return ( ((Boolean) ((((Integer) (n_prime__1)) < ((Integer) (new Integer(1)))))) ? (((Integer) (n_prime__1)) + ((Integer) (new Integer(2147483646)))) : n_prime__1); };
public static final Object randomSeed = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_0 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Effect_Random.randomInt)).apply(new Integer(1)))).apply(new Integer(2147483646)); return __local_var_0; } }).get();
public static final Object lcgC = new Integer(0);
public static final Object lcgA = new Integer(48271);
public static final Object lcgPerturb = (java.util.function.Function<Object, Object>) (d_0) -> (java.util.function.Function<Object, Object>) (v_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (Data_Int.fromNumber)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Number.remainder)).apply((((Double) ((((Double) (((java.util.function.Function<Object, Object>) (Data_Int.toNumber)).apply(new Integer(48271)))) * ((Double) (((java.util.function.Function<Object, Object>) (Data_Int.toNumber)).apply(v_1)))))) + ((Double) (((java.util.function.Function<Object, Object>) (Data_Int.toNumber)).apply(d_0))))))).apply(((java.util.function.Function<Object, Object>) (Data_Int.toNumber)).apply(new Integer(2147483647)))); return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) __local_var_2).value0) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get()); };
public static final Object lcgNext = ((java.util.function.Function<Object, Object>) (Random_LCG.lcgPerturb)).apply(new Integer(0));
public static final Object eqSeed = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> (((Integer) (x_0)) == ((Integer) (y_1))));  return __map; } }).get();
public static final Object ordSeed = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("compare", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(x_0))).apply(y_1)); __map.put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Random_LCG.eqSeed);  return __map; } }).get();
}
