public class Record {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object union = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (l_1) -> (java.util.function.Function<Object, Object>) (r_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe_Union.unsafeUnionFn)).apply(l_1))).apply(r_2);
public static final Object set = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (b_4) -> (java.util.function.Function<Object, Object>) (r_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeSet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l_3)))).apply(b_4))).apply(r_5);
public static final Object nub = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Unsafe_Coerce.unsafeCoerce;
public static final Object merge = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (l_2) -> (java.util.function.Function<Object, Object>) (r_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe_Union.unsafeUnionFn)).apply(l_2))).apply(r_3);
public static final Object insert = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (a_4) -> (java.util.function.Function<Object, Object>) (r_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeSet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l_3)))).apply(a_4))).apply(r_5);
public static final Object get = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (l_2) -> (java.util.function.Function<Object, Object>) (r_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l_2)))).apply(r_3);
public static final Object modify = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (f_4) -> (java.util.function.Function<Object, Object>) (r_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeSet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l_3)))).apply(((java.util.function.Function<Object, Object>) (f_4)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l_3)))).apply(r_5))))).apply(r_5);
public static final Object equalFieldsNil = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("equalFields", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> new Boolean(true));  return __map; } }).get();
public static final Object equalFields = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("equalFields");
public static final Object equalFieldsCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (dictEq_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (dictEqualFields_3) -> (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("equalFields", (java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (a_5) -> (java.util.function.Function<Object, Object>) (b_6) -> (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_1).get("eq"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(new Type_Proxy.Proxy())))).apply(a_5)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(new Type_Proxy.Proxy())))).apply(b_6)))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEqualFields_3).get("equalFields"))).apply(new Type_Proxy.Proxy()))).apply(a_5))).apply(b_6)))));  return __map; } }).get();
public static final Object equal = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (dictEqualFields_1) -> (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEqualFields_1).get("equalFields"))).apply(new Type_Proxy.Proxy()))).apply(a_2))).apply(b_3);
public static final Object disjointUnion = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (l_2) -> (java.util.function.Function<Object, Object>) (r_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe_Union.unsafeUnionFn)).apply(l_2))).apply(r_3);
public static final Object delete = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (r_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeDelete)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l_3)))).apply(r_4);
public static final Object rename = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (dictIsSymbol1_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> (java.util.function.Function<Object, Object>) (_dollar___unused_5) -> (java.util.function.Function<Object, Object>) (prev_6) -> (java.util.function.Function<Object, Object>) (next_7) -> (java.util.function.Function<Object, Object>) (record_8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeSet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol1_1).get("reflectSymbol"))).apply(next_7)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(prev_6)))).apply(record_8)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeDelete)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(prev_6)))).apply(record_8));
}
