public class Record_Builder {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object copyRecord = FFI_STUB;
    public static Object copyRecord(Object... args) { return null; }
    public static Object unsafeDelete = FFI_STUB;
    public static Object unsafeDelete(Object... args) { return null; }
    public static Object unsafeInsert = FFI_STUB;
    public static Object unsafeInsert(Object... args) { return null; }
    public static Object unsafeModify = FFI_STUB;
    public static Object unsafeModify(Object... args) { return null; }
    public static Object unsafeRename = FFI_STUB;
    public static Object unsafeRename(Object... args) { return null; }

public static final Object union = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (r1_1) -> (java.util.function.Function<Object, Object>) (r2_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe_Union.unsafeUnionFn)).apply(r1_1))).apply(r2_2);
public static final Object semigroupoidBuilder = Control_Semigroupoid.semigroupoidFn;
public static final Object rename = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (dictIsSymbol1_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> (java.util.function.Function<Object, Object>) (_dollar___unused_5) -> (java.util.function.Function<Object, Object>) (l1_6) -> (java.util.function.Function<Object, Object>) (l2_7) -> (java.util.function.Function<Object, Object>) (r1_8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Builder.unsafeRename)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l1_6)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol1_1).get("reflectSymbol"))).apply(l2_7)))).apply(r1_8);
public static final Object nub = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Unsafe_Coerce.unsafeCoerce;
public static final Object modify = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (dictIsSymbol_2) -> (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (f_4) -> (java.util.function.Function<Object, Object>) (r1_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Builder.unsafeModify)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_2).get("reflectSymbol"))).apply(l_3)))).apply(f_4))).apply(r1_5);
public static final Object merge = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (r1_2) -> (java.util.function.Function<Object, Object>) (r2_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe_Union.unsafeUnionFn)).apply(r1_2))).apply(r2_3);
public static final Object insert = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (dictIsSymbol_2) -> (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (a_4) -> (java.util.function.Function<Object, Object>) (r1_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Builder.unsafeInsert)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_2).get("reflectSymbol"))).apply(l_3)))).apply(a_4))).apply(r1_5);
public static final Object disjointUnion = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (r1_2) -> (java.util.function.Function<Object, Object>) (r2_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe_Union.unsafeUnionFn)).apply(r1_2))).apply(r2_3);
public static final Object delete = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (r2_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Builder.unsafeDelete)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(l_3)))).apply(r2_4);
public static final Object categoryBuilder = Control_Category.categoryFn;
public static final Object build = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (r1_1) -> ((java.util.function.Function<Object, Object>) (v_0)).apply(((java.util.function.Function<Object, Object>) (Record_Builder.copyRecord)).apply(r1_1));
public static final Object buildFromScratch = (java.util.function.Function<Object, Object>) (a_0) -> ((java.util.function.Function<Object, Object>) (a_0)).apply((new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>();  return __map; } }).get());
public static final Object flip = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0)).apply(a_2))).apply(((java.util.function.Function<Object, Object>) (Record_Builder.copyRecord)).apply(b_1));
}
