public class Test_QuickCheck_Laws_Data_Enum {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkEnumGen = (java.util.function.Function<Object, Object>) (dictEnum_0) -> { Object Ord0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEnum_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); Object eqMaybe_2 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEnum_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */)).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq", (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ( ((Boolean) ((x_3 instanceof Data_Maybe.Nothing))) ? (y_4 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_3 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_4 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("eq"))).apply((((Data_Maybe.Just) x_3).value0)))).apply((((Data_Maybe.Just) y_4).value0))))))))));  return __map; } }).get(); } }).get(); return (java.util.function.Function<Object, Object>) (dictOrd_3) -> (java.util.function.Function<Object, Object>) (gen_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Successor' law for Enum"); return __local_var_5; }; };
public static final Object checkEnum = (java.util.function.Function<Object, Object>) (dictArbitrary_0) -> { Object arbitrary_1 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_0).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictEnum_2) -> (java.util.function.Function<Object, Object>) (dictOrd_3) -> (java.util.function.Function<Object, Object>) (v_4) -> { Object Ord0_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEnum_2).get("Ord0"))).apply(null /* TODO: PrimUndefined */); Object eqMaybe_6 = (new java.util.function.Supplier<Object>() { public Object get() { Object __local_var_6 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEnum_2).get("Ord0"))).apply(null /* TODO: PrimUndefined */)).get("Eq0"))).apply(null /* TODO: PrimUndefined */); return (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("eq", (java.util.function.Function<Object, Object>) (x_7) -> (java.util.function.Function<Object, Object>) (y_8) -> ( ((Boolean) ((x_7 instanceof Data_Maybe.Nothing))) ? (y_8 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_7 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_8 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_6).get("eq"))).apply((((Data_Maybe.Just) x_7).value0)))).apply((((Data_Maybe.Just) y_8).value0))))))))));  return __map; } }).get(); } }).get(); Object __local_var_7 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Successor' law for Enum"); return __local_var_7; }; };
}
