public class Test_QuickCheck_Laws_Data_Foldable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object testableFunction = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("test", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (s_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.elements)).apply(new Object[]{new Data_Ordering.LT(), new Data_Ordering.EQ(), new Data_Ordering.GT()}))).apply(s_1); return ( ((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply((((Data_Tuple.Tuple) __local_var_2).value0)))) ? new Data_Tuple.Tuple(new Test_QuickCheck.Success(), (((Data_Tuple.Tuple) __local_var_2).value1)) : new Data_Tuple.Tuple(new Test_QuickCheck.Failed("Test returned false"), (((Data_Tuple.Tuple) __local_var_2).value1))); });  return __map; } }).get();
public static final Object checkFoldableGen = (java.util.function.Function<Object, Object>) (dictFoldable_0) -> (java.util.function.Function<Object, Object>) (gen_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'foldr' law for Foldable"); return __local_var_2; };
public static final Object checkFoldableFunctorGen = (java.util.function.Function<Object, Object>) (dictFoldable_0) -> { Object fold_1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFoldable_0).get("foldMap"))).apply(Test_QuickCheck_Laws.monoidB))).apply((java.util.function.Function<Object, Object>) (x_1) -> x_1); return (java.util.function.Function<Object, Object>) (dictFunctor_2) -> (java.util.function.Function<Object, Object>) (gen_3) -> { Object __local_var_4 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'foldr' law for Foldable"); return __local_var_4; }; };
public static final Object checkFoldableFunctor = (java.util.function.Function<Object, Object>) (dictFoldable_0) -> (java.util.function.Function<Object, Object>) (dictFunctor_1) -> (java.util.function.Function<Object, Object>) (dictArbitrary_2) -> (java.util.function.Function<Object, Object>) (v_3) -> { Object fold_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFoldable_0).get("foldMap"))).apply(Test_QuickCheck_Laws.monoidB))).apply((java.util.function.Function<Object, Object>) (x_4) -> x_4); Object __local_var_5 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'foldr' law for Foldable"); return __local_var_5; };
public static final Object checkFoldable = (java.util.function.Function<Object, Object>) (dictFoldable_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> (java.util.function.Function<Object, Object>) (v_2) -> { Object __local_var_3 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'foldr' law for Foldable"); return __local_var_3; };
}
