public class Test_QuickCheck_Laws_Data_Ring {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkRingGen = (java.util.function.Function<Object, Object>) (dictRing_0) -> { Object zero_1 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero"); Object Semiring0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (gen_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Additive inverse' law for Ring"); return __local_var_5; }; };
public static final Object checkRing = (java.util.function.Function<Object, Object>) (dictRing_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (v_3) -> { Object zero_4 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero"); Object Semiring0_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_0).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object __local_var_6 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Additive inverse' law for Ring"); return __local_var_6; };
}
