public class Test_QuickCheck_Laws_Control_Extend {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkExtendGen = (java.util.function.Function<Object, Object>) (dictExtend_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> (java.util.function.Function<Object, Object>) (dictCoarbitrary_2) -> (java.util.function.Function<Object, Object>) (dictCoarbitrary1_3) -> (java.util.function.Function<Object, Object>) (dictEq_4) -> (java.util.function.Function<Object, Object>) (gen_5) -> (java.util.function.Function<Object, Object>) (genwbc_6) -> (java.util.function.Function<Object, Object>) (genwab_7) -> { Object __local_var_8 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associativity' law for Extend"); return __local_var_8; };
public static final Object checkExtend = (java.util.function.Function<Object, Object>) (dictExtend_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictCoarbitrary_3) -> { Object arbitrary1_4 = (new java.util.function.Supplier<Object>() { public Object get() { Object arbitrary1_4 = ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.elements)).apply(new Object[]{new Data_Ordering.LT(), new Data_Ordering.EQ(), new Data_Ordering.GT()}); return ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.repeatable)).apply((java.util.function.Function<Object, Object>) (a_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCoarbitrary_3).get("coarbitrary"))).apply(a_5))).apply(arbitrary1_4)); } }).get(); return (java.util.function.Function<Object, Object>) (dictCoarbitrary1_5) -> { Object arbitrary2_6 = (new java.util.function.Supplier<Object>() { public Object get() { Object arbitrary1_6 = ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.elements)).apply(new Object[]{new Data_Ordering.LT(), new Data_Ordering.EQ(), new Data_Ordering.GT()}); return ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.repeatable)).apply((java.util.function.Function<Object, Object>) (a_7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCoarbitrary1_5).get("coarbitrary"))).apply(a_7))).apply(arbitrary1_6)); } }).get(); return (java.util.function.Function<Object, Object>) (dictEq_7) -> (java.util.function.Function<Object, Object>) (v_8) -> { Object __local_var_9 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associativity' law for Extend"); return __local_var_9; }; }; }; };
}
