public class Test_QuickCheck_Laws_Control_Comonad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkComonadGen = (java.util.function.Function<Object, Object>) (dictComonad_0) -> { Object Extend0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictComonad_0).get("Extend0"))).apply(null /* TODO: PrimUndefined */); Object extract_2 = ((java.util.LinkedHashMap<String, Object>) dictComonad_0).get("extract"); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (gen_4) -> (java.util.function.Function<Object, Object>) (cogen_5) -> { Object __local_var_6 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Comonad"); return __local_var_6; }; };
public static final Object checkComonad = (java.util.function.Function<Object, Object>) (dictComonad_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictCoarbitrary_3) -> { Object arbitrary1_4 = (new java.util.function.Supplier<Object>() { public Object get() { Object arbitrary1_4 = ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.elements)).apply(new Object[]{new Data_Ordering.LT(), new Data_Ordering.EQ(), new Data_Ordering.GT()}); return ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.repeatable)).apply((java.util.function.Function<Object, Object>) (a_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCoarbitrary_3).get("coarbitrary"))).apply(a_5))).apply(arbitrary1_4)); } }).get(); return (java.util.function.Function<Object, Object>) (dictEq_5) -> (java.util.function.Function<Object, Object>) (v_6) -> { Object Extend0_7 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictComonad_0).get("Extend0"))).apply(null /* TODO: PrimUndefined */); Object extract_8 = ((java.util.LinkedHashMap<String, Object>) dictComonad_0).get("extract"); Object __local_var_9 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Comonad"); return __local_var_9; }; }; };
}
