public class Test_QuickCheck_Laws_Data_BooleanAlgebra {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkBooleanAlgebraGen = (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_0) -> { Object HeytingAlgebra0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebra_0).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */); Object tt_2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebra_0).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */)).get("tt"); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (gen_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Excluded middle' law for BooleanAlgebra"); return __local_var_5; }; };
public static final Object checkBooleanAlgebra = (java.util.function.Function<Object, Object>) (dictArbitrary_0) -> (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_1) -> (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (v_3) -> { Object HeytingAlgebra0_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebra_1).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */); Object tt_5 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebra_1).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */)).get("tt"); Object __local_var_6 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Excluded middle' law for BooleanAlgebra"); return __local_var_6; };
}
