public class Test_QuickCheck_Laws_Control_Applicative {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object testableFunction = (new java.util.function.Supplier<Object>() { public Object get() { java.util.Map<String, Object> __map = new java.util.LinkedHashMap<>(); __map.put("test", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (s_1) -> { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.elements)).apply(new Object[]{new Data_Ordering.LT(), new Data_Ordering.EQ(), new Data_Ordering.GT()}))).apply(s_1); return ( ((Boolean) (((java.util.function.Function<Object, Object>) (f_0)).apply((((Data_Tuple.Tuple) __local_var_2).value0)))) ? new Data_Tuple.Tuple(new Test_QuickCheck.Success(), (((Data_Tuple.Tuple) __local_var_2).value1)) : new Data_Tuple.Tuple(new Test_QuickCheck.Failed("Test returned false"), (((Data_Tuple.Tuple) __local_var_2).value1))); });  return __map; } }).get();
public static final Object checkApplicativeGen = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> { Object Apply0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (dictEq1_3) -> (java.util.function.Function<Object, Object>) (dictEq2_4) -> (java.util.function.Function<Object, Object>) (gen_5) -> (java.util.function.Function<Object, Object>) (genab_6) -> (java.util.function.Function<Object, Object>) (genbc_7) -> { Object __local_var_8 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Identity' law for Applicative"); return __local_var_8; }; };
public static final Object checkApplicative = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictArbitrary1_3) -> { Object arbitrary1_4 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary1_3).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictArbitrary2_5) -> { Object arbitrary2_6 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary2_5).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictEq_7) -> (java.util.function.Function<Object, Object>) (dictEq1_8) -> (java.util.function.Function<Object, Object>) (dictEq2_9) -> (java.util.function.Function<Object, Object>) (v_10) -> { Object Apply0_11 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); Object __local_var_12 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Identity' law for Applicative"); return __local_var_12; }; }; }; };
}
