public class Test_QuickCheck_Laws_Control_Apply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkApplyGen = (java.util.function.Function<Object, Object>) (dictApply_0) -> { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (gen_3) -> (java.util.function.Function<Object, Object>) (genab_4) -> (java.util.function.Function<Object, Object>) (genbc_5) -> { Object __local_var_6 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associative composition' law for Apply"); return __local_var_6; }; };
public static final Object checkApply = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictArbitrary1_3) -> { Object arbitrary1_4 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary1_3).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictArbitrary2_5) -> { Object arbitrary2_6 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary2_5).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictEq_7) -> (java.util.function.Function<Object, Object>) (v_8) -> { Object Functor0_9 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object __local_var_10 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associative composition' law for Apply"); return __local_var_10; }; }; }; };
}
