public class Test_QuickCheck_Laws_Control_MonadPlus {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkMonadPlusGen = (java.util.function.Function<Object, Object>) (dictMonadPlus_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadPlus_0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Alt0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadPlus_0).get("Alternative1"))).apply(null /* TODO: PrimUndefined */)).get("Plus1"))).apply(null /* TODO: PrimUndefined */)).get("Alt0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (gen_4) -> (java.util.function.Function<Object, Object>) (genf_5) -> { Object __local_var_6 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Distributivity' law for MonadPlus"); return __local_var_6; }; };
public static final Object checkMonadPlus = (java.util.function.Function<Object, Object>) (dictMonadPlus_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictArbitrary1_3) -> { Object arbitrary1_4 = (new java.util.function.Supplier<Object>() { public Object get() { Object arbitrary1_4 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary1_3).get("arbitrary"); return ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.repeatable)).apply((java.util.function.Function<Object, Object>) (a_5) -> ( ((Boolean) ((a_5 instanceof Data_Ordering.LT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(1.0)))).apply(arbitrary1_4) : ( ((Boolean) ((a_5 instanceof Data_Ordering.EQ))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(2.0)))).apply(arbitrary1_4) : ( ((Boolean) ((a_5 instanceof Data_Ordering.GT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(3.0)))).apply(arbitrary1_4) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())))); } }).get(); return (java.util.function.Function<Object, Object>) (dictEq_5) -> (java.util.function.Function<Object, Object>) (v_6) -> { Object Bind1_7 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadPlus_0).get("Monad0"))).apply(null /* TODO: PrimUndefined */)).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object Alt0_8 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadPlus_0).get("Alternative1"))).apply(null /* TODO: PrimUndefined */)).get("Plus1"))).apply(null /* TODO: PrimUndefined */)).get("Alt0"))).apply(null /* TODO: PrimUndefined */); Object __local_var_9 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Distributivity' law for MonadPlus"); return __local_var_9; }; }; };
}
