public class Test_QuickCheck_Laws_Control_Plus {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkPlusGen = (java.util.function.Function<Object, Object>) (dictPlus_0) -> { Object Alt0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictPlus_0).get("Alt0"))).apply(null /* TODO: PrimUndefined */); Object empty_2 = ((java.util.LinkedHashMap<String, Object>) dictPlus_0).get("empty"); Object Functor0_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictPlus_0).get("Alt0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictEq_4) -> (java.util.function.Function<Object, Object>) (dictEq1_5) -> (java.util.function.Function<Object, Object>) (gen_6) -> { Object __local_var_7 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Plus"); return __local_var_7; }; };
public static final Object checkPlus = (java.util.function.Function<Object, Object>) (dictPlus_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (dictEq1_3) -> (java.util.function.Function<Object, Object>) (v_4) -> { Object Alt0_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictPlus_0).get("Alt0"))).apply(null /* TODO: PrimUndefined */); Object empty_6 = ((java.util.LinkedHashMap<String, Object>) dictPlus_0).get("empty"); Object Functor0_7 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictPlus_0).get("Alt0"))).apply(null /* TODO: PrimUndefined */)).get("Functor0"))).apply(null /* TODO: PrimUndefined */); Object __local_var_8 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Plus"); return __local_var_8; };
}
