public class Test_QuickCheck_Laws_Data_Field {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkFieldGen = (java.util.function.Function<Object, Object>) (dictField_0) -> { Object EuclideanRing0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictField_0).get("EuclideanRing0"))).apply(null /* TODO: PrimUndefined */); Object zero_2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictField_0).get("DivisionRing1"))).apply(null /* TODO: PrimUndefined */)).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero"); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (gen_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Non-zero multiplicative inverse' law for Field"); return __local_var_5; }; };
public static final Object checkField = (java.util.function.Function<Object, Object>) (dictField_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (v_4) -> { Object EuclideanRing0_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictField_0).get("EuclideanRing0"))).apply(null /* TODO: PrimUndefined */); Object zero_6 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictField_0).get("DivisionRing1"))).apply(null /* TODO: PrimUndefined */)).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero"); Object __local_var_7 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Non-zero multiplicative inverse' law for Field"); return __local_var_7; }; };
}
