public class Test_QuickCheck_Laws_Data_DivisionRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkDivisionRingGen = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> { Object Ring0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */); Object Semiring0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object one_3 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2).get("one"); Object zero_4 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2).get("zero"); Object Semiring01_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictEq_6) -> (java.util.function.Function<Object, Object>) (gen_7) -> { Object nonZero_8 = !(((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_6).get("eq"))).apply(one_3))).apply(zero_4)))); Object __local_var_9 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Non-zero ring' law for DivisionRing"); return __local_var_9; }; };
public static final Object checkDivisionRing = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (v_3) -> { Object Ring0_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */); Object Semiring0_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_4).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object one_6 = ((java.util.LinkedHashMap<String, Object>) Semiring0_5).get("one"); Object zero_7 = ((java.util.LinkedHashMap<String, Object>) Semiring0_5).get("zero"); Object Semiring01_8 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_4).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object nonZero_9 = !(((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_2).get("eq"))).apply(one_6))).apply(zero_7)))); Object __local_var_10 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Non-zero ring' law for DivisionRing"); return __local_var_10; };
}
