public class Test_QuickCheck_Laws_Data_EuclideanRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkEuclideanRingGen = (java.util.function.Function<Object, Object>) (dictEuclideanRing_0) -> { Object Ring0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEuclideanRing_0).get("CommutativeRing0"))).apply(null /* TODO: PrimUndefined */)).get("Ring0"))).apply(null /* TODO: PrimUndefined */); Object Semiring0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object zero1_3 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2).get("zero"); Object Semiring01_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object one_5 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2).get("one"); return (java.util.function.Function<Object, Object>) (dictEq_6) -> (java.util.function.Function<Object, Object>) (gen_7) -> { Object __local_var_8 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Integral domain' law for EuclideanRing"); return __local_var_8; }; };
public static final Object checkEuclideanRing = (java.util.function.Function<Object, Object>) (dictEuclideanRing_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (v_4) -> { Object Ring0_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEuclideanRing_0).get("CommutativeRing0"))).apply(null /* TODO: PrimUndefined */)).get("Ring0"))).apply(null /* TODO: PrimUndefined */); Object Semiring0_6 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_5).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object zero1_7 = ((java.util.LinkedHashMap<String, Object>) Semiring0_6).get("zero"); Object Semiring01_8 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Ring0_5).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); Object one_9 = ((java.util.LinkedHashMap<String, Object>) Semiring0_6).get("one"); Object __local_var_10 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Integral domain' law for EuclideanRing"); return __local_var_10; }; };
}
