public class Test_QuickCheck_Laws_Control_Alternative {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkAlternativeGen = (java.util.function.Function<Object, Object>) (dictAlternative_0) -> { Object Apply0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlternative_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */); Object Plus1_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlternative_0).get("Plus1"))).apply(null /* TODO: PrimUndefined */); Object Alt0_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Plus1_2).get("Alt0"))).apply(null /* TODO: PrimUndefined */); Object empty_4 = ((java.util.LinkedHashMap<String, Object>) Plus1_2).get("empty"); Object empty1_5 = ((java.util.LinkedHashMap<String, Object>) Plus1_2).get("empty"); return (java.util.function.Function<Object, Object>) (dictEq_6) -> (java.util.function.Function<Object, Object>) (dictEq1_7) -> (java.util.function.Function<Object, Object>) (gen_8) -> (java.util.function.Function<Object, Object>) (genf_9) -> (java.util.function.Function<Object, Object>) (v_10) -> { Object __local_var_11 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Alternative"); return __local_var_11; }; };
public static final Object checkAlternative = (java.util.function.Function<Object, Object>) (dictAlternative_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictArbitrary1_3) -> { Object arbitrary1_4 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary1_3).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictEq_5) -> (java.util.function.Function<Object, Object>) (dictEq1_6) -> { Object Apply0_7 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlternative_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("Apply0"))).apply(null /* TODO: PrimUndefined */); Object Plus1_8 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlternative_0).get("Plus1"))).apply(null /* TODO: PrimUndefined */); Object Alt0_9 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Plus1_8).get("Alt0"))).apply(null /* TODO: PrimUndefined */); Object empty_10 = ((java.util.LinkedHashMap<String, Object>) Plus1_8).get("empty"); Object empty1_11 = ((java.util.LinkedHashMap<String, Object>) Plus1_8).get("empty"); return (java.util.function.Function<Object, Object>) (v_12) -> { Object __local_var_13 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Alternative"); return __local_var_13; }; }; }; };
}
