public class Test_QuickCheck_Laws_Control_Monad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkMonadGen = (java.util.function.Function<Object, Object>) (dictMonad_0) -> { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object pure_2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"); Object Applicative0_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); return (java.util.function.Function<Object, Object>) (dictEq_4) -> (java.util.function.Function<Object, Object>) (gen_5) -> (java.util.function.Function<Object, Object>) (genf_6) -> { Object __local_var_7 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Monad"); return __local_var_7; }; };
public static final Object checkMonad = (java.util.function.Function<Object, Object>) (dictMonad_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary1_2 = (new java.util.function.Supplier<Object>() { public Object get() { Object arbitrary1_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.repeatable)).apply((java.util.function.Function<Object, Object>) (a_3) -> ( ((Boolean) ((a_3 instanceof Data_Ordering.LT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(1.0)))).apply(arbitrary1_2) : ( ((Boolean) ((a_3 instanceof Data_Ordering.EQ))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(2.0)))).apply(arbitrary1_2) : ( ((Boolean) ((a_3 instanceof Data_Ordering.GT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(3.0)))).apply(arbitrary1_2) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())))); } }).get(); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (v_4) -> { Object Bind1_5 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); Object pure_6 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */)).get("pure"); Object Applicative0_7 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); Object __local_var_8 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Left identity' law for Monad"); return __local_var_8; }; };
}
