public class Test_QuickCheck_Laws_Control_Bind {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkBindGen = (java.util.function.Function<Object, Object>) (dictBind_0) -> (java.util.function.Function<Object, Object>) (dictEq_1) -> (java.util.function.Function<Object, Object>) (gen_2) -> (java.util.function.Function<Object, Object>) (genF_3) -> { Object __local_var_4 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associativity' law for Bind"); return __local_var_4; };
public static final Object checkBind = (java.util.function.Function<Object, Object>) (dictBind_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); Object arbitrary1_3 = (new java.util.function.Supplier<Object>() { public Object get() { Object arbitrary1_3 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return ((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.repeatable)).apply((java.util.function.Function<Object, Object>) (a_4) -> ( ((Boolean) ((a_4 instanceof Data_Ordering.LT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(1.0)))).apply(arbitrary1_3) : ( ((Boolean) ((a_4 instanceof Data_Ordering.EQ))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(2.0)))).apply(arbitrary1_3) : ( ((Boolean) ((a_4 instanceof Data_Ordering.GT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Test_QuickCheck_Gen.perturbGen)).apply(new Double(3.0)))).apply(arbitrary1_3) : (new java.util.function.Supplier<Object>() { public Object get() { throw new RuntimeException("Failed pattern match"); } }).get())))); } }).get(); return (java.util.function.Function<Object, Object>) (dictEq_4) -> (java.util.function.Function<Object, Object>) (v_5) -> { Object __local_var_6 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associativity' law for Bind"); return __local_var_6; }; };
}
