public class Test_QuickCheck_Laws_Data_Semiring {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object checkSemiringGen = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> { Object one_1 = ((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("one"); Object zero_2 = ((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("zero"); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (gen_4) -> { Object __local_var_5 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associativity' law for Semiring addition"); return __local_var_5; }; };
public static final Object checkSemiring = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> (java.util.function.Function<Object, Object>) (dictArbitrary_1) -> { Object arbitrary_2 = ((java.util.LinkedHashMap<String, Object>) dictArbitrary_1).get("arbitrary"); return (java.util.function.Function<Object, Object>) (dictEq_3) -> (java.util.function.Function<Object, Object>) (v_4) -> { Object one_5 = ((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("one"); Object zero_6 = ((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("zero"); Object __local_var_7 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply("Checking 'Associativity' law for Semiring addition"); return __local_var_7; }; };
}
